### PR TITLE
Added PyPy to the build

### PR DESCRIPTION
**Pull request by thedrow**

### CODE REVIEW

**Comment by piskvorky** [comment]
Thanks @thedrow . The Travis build on PyPy is failing though -- can you check what's going on?

**Comment by thedrow** [comment]
It seems that the database is locked when you use multithreading in SQLite with PyPy.
See https://travis-ci.org/piskvorky/sqlitedict/jobs/72578760#L158
No idea how to fix it though.

**Comment by piskvorky** [comment]
I don't know how threading works in PyPy either :(

It must be something specific to PyPy, because threading is handled explicitly in sqlite(dict).

**Comment by thedrow** [comment]
I'll leave this open until I have time to take a look at it.

**Comment by piskvorky** [comment]
@thedrow any luck with this ticket?

**Comment by thedrow** [comment]
No, sorry.

**Comment by piskvorky** [comment]
Can you try `pypy3` instead of `pypy`? Maybe it's just some version mismatch...

**Comment by menshikh-iv** [comment]
I test it in #70, the same problem for both `pypy` versions, it doesn't work, I close current PR.

**Pull request closed without merging**
