### PR TITLE
Clean up license file names

### PR DESCRIPTION
**Pull request by r-barnes**
Removes one license file, renames the other. The result is that Github recognizes the license automagically:

Github recognizes license

### CODE REVIEW

**Comment by piskvorky** [comment]
Is it safe to delete `LICENSE.rst`? What was it there for? (= what broke after its removal)

**Comment by r-barnes** [comment]
It was good to check: I fixed references in MANIFEST.in. As to its original purpose, I don't know.

It's not Github, because this PR is to fix the problem on GitHub. There's a travis file, but CI isn't enabled for PRs, so I'm not sure how to test. I don't see documentation for PyPI discussing a "license.rst" file.

**Comment by r-barnes** [comment]
@toddrme2178 added the file. Can they speak to this?

**Comment by mpenkov** [comment]
This looks like it's good to merge.

**Pull request merged**
