### PR TITLE
Change logging from info to debug

### PR DESCRIPTION
**Pull request by nvllsvm**
**What**
Change the the database-open log from info-level to debug-level

**Why**
It's an implementation detail that one does not need to care about while using this library.

### CODE REVIEW

**Comment by mpenkov** [comment]
Dunno, I think your changes are OK, but I also think it's fine the way it is, because:

1. This log statement gets executed rarely
2. Whether or not people care about this statement is really up to them
3. If they **really** don't care, then they can set the logging level to something else when configuring the logging library

@piskvorky thoughts?

**Comment by piskvorky** [comment]
I'd keep it as-is, mostly on account of your point 3). That's the reason why we use logging, so that people can configure the threshold the way they like.

While it's true there is always some subjective arbitrariness in what is considered DEBUG (for developers) vs INFO (generally useful info to users but nothing vital), IMO "opening a database" falls squarely into INFO.

@nvllsvm why does it bother you?

**Comment by nvllsvm** [comment]
Let me start by saying that I understand I'm being fairly pedantic about not liking the default of an info-level log entry. Thank you for discussing with me.

> why does it bother you?

It's unexpected to have an otherwise unopinionated library output info-level statements by default.  like the stdlib's **sqlite3** and the popular **pycopg** do not output anything info-level when connecting to their respective databases. Tangentially, neither **httpx** not **requests** output info-level when making an HTTP request. These libraries delegate that responsibility to the developer using them.

For example, the only log entry output by this dict is from sqlitedict
```
import logging
import sqlite3

import psycopg
import requests
import sqlitedict

logging.basicConfig(level=logging.INFO)

sqlite3.connect('test.sqlite')
psycopg.connect('postgresql://somedb')
requests.get('https://github.com')
sqlitedict.SqliteDict('test.sqlitedict')
```
```
INFO:sqlitedict:opening Sqlite table 'unnamed' in 'test.sqlitedict'
```

**Comment by mpenkov** [comment]
> That log entry is unnecessary noise in log output - especially when the output is shared with someone unfamiliar with sqlitedict or when multiple files are being used.

OK, that's a reasonable point.

**Review by mpenkov — APPROVED** [review]

**Comment by mpenkov** [comment]
Merged, thank you for your effort and explanation.

**Pull request merged**
